sudo: required
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
before_install:
 - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-27"
before_script:
 - chmod +x gradlew
script:
 - ./gradlew build
